[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "report-bot"
version = "0.1.0"
description = "Daily & Weekly Git Report CLI"
dependencies = [
  "typer",
  "gitpython",
]

[project.scripts]
report = "report.cli:main"
